# COLORS
GREEN  := $(shell tput -Txterm setaf 2)
YELLOW := $(shell tput -Txterm setaf 3)
WHITE  := $(shell tput -Txterm setaf 7)
RESET  := $(shell tput -Txterm sgr0)

CC=gcc
CFLAGS= -c -Wall
BINARIES=client.o binn.o server.o

TARGET_MAX_CHAR_NUM=20

## Show help
help:
	@echo ''
	@echo 'Help: Prints Help Info'
	@echo '  ${YELLOW}make${RESET} ${GREEN}help${RESET}'
	@echo ''
	@echo 'all: Builds both Client and Server'
	@echo '  ${YELLOW}make${RESET} ${GREEN}all${RESET}'
	@echo ''
	@echo 'client: Builds Client output name client'
	@echo '  ${YELLOW}make${RESET} ${GREEN}client${RESET}'
	@echo ''
	@echo 'clean: Removes all object files generated by this make'
	@echo '  ${YELLOW}make${RESET} ${GREEN}clean${RESET}'

##Generates Client and Server with all dependancies
all: client server

##Compiles client object and links required binn object
client: client.o binn.o
	$(CC) client.o binn.o -o client

##Compiles the client object
client.o: client.c binn.h
	$(CC) $(CFLAGS) client.c

##compiles the binn object
binn.o: binn.c binn.h
	$(CC) $(CFLAGS) binn.c

##compiles the server
server: server.o binn.o
	$(CC) server.o binn.o -o server

##compiles the server object
server.o: server.c binn.h
	$(CC) $(CFLAGS) server.c

##Removes all files generated by this makefile
clean:
		rm -f $(BINARIES) *.o
		@echo 'Clean Done'
